### ISSUE TITLE
SSLHandshakeException CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by cesine** [FieldDB/FieldDB#2151]
```java
12-26 12:12:34.429 25300 25907 D OPrime  : Uploading audio video
12-26 12:12:34.543  3518  3555 D StreamDBQueue: Promised revision #42624 to queue a new op
12-26 12:12:34.543  3518  3555 D BaseStreamManager: Promised set @ r#42624 for (com.github.old.fdb.speech.kartuli,tag=null,id=-1836701076,notifKey=0|com.github.old.fdb.speech.kartuli|-1836701076|null|10167)
12-26 12:12:34.546  3518  3566 D DynamicBucketRankerImpl: StreamItemId{notifKey=0|com.github.old.fdb.speech.kartuli|-1836701076|null|10167, packageName=com.github.old.fdb.speech.kartuli, id=-1836701076, revision=42624, originalRevision=42624, updateCount=0} in bucket #8 (Other)
12-26 12:12:34.546  3518  3566 D WatchStreamDB: com.google.android.clockwork.common.stream.TopLevelStreamItem@2938d00 ranked at index 3
12-26 12:12:34.546  3518  3566 D NewStreamAdapter: Publishing revision #42624 to adapter clients
12-26 12:12:34.711 25300 25310 I zygote  : Background concurrent copying GC freed 23461(1185KB) AllocSpace objects, 3(56KB) LOS objects, 49% free, 3MB/7MB, paused 5.154ms total 41.656ms
12-26 12:12:34.762  3518  3555 I NotificationBridger: Ignoring change event for bridged-notification data item
12-26 12:12:35.191  5382 24175 W ctxmgr  : [AclManager]No 2 for (accnt=account#-2069259777#, com.google.android.gms(10020):UserLocationProducer, vrsn=11951000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 5382). Was: 2 for 1, account#-2069259777#
12-26 12:12:35.194  5382 24175 W ctxmgr  : [AclManager]No 2 for (accnt=account#-617804067#, com.google.android.gms(10020):UserLocationProducer, vrsn=11951000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 5382). Was: 2 for 1, account#-617804067#
12-26 12:12:35.218 25300 25907 W System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
12-26 12:12:35.241 25300 25907 W System.err:  at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:219)
12-26 12:12:35.241 25300 25907 W System.err:  at org.apache.http.conn.ssl.SSLSocketFactory.createSocket(SSLSocketFactory.java:406)
12-26 12:12:35.241 25300 25907 W System.err:  at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:170)
12-26 12:12:35.241 25300 25907 W System.err:  at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:169)
12-26 12:12:35.241 25300 25907 W System.err:  at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:124)
12-26 12:12:35.241 25300 25907 W System.err:  at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:366)
12-26 12:12:35.241 25300 25907 W System.err:  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
12-26 12:12:35.241 25300 25907 W System.err:  at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
12-26 12:12:35.241 25300 25907 W System.err:  at com.github.old.fdb.service.UploadAudioVideoService.upload(UploadAudioVideoService.java:210)
12-26 12:12:35.241 25300 25907 W System.err:  at com.github.old.fdb.service.UploadAudioVideoService.onHandleIntent(UploadAudioVideoService.java:127)
12-26 12:12:35.241 25300 25907 W System.err:  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
12-26 12:12:35.241 25300 25907 W System.err:  at android.os.Handler.dispatchMessage(Handler.java:106)
12-26 12:12:35.241 25300 25907 W System.err:  at android.os.Looper.loop(Looper.java:164)
12-26 12:12:35.241 25300 25907 W System.err:  at android.os.HandlerThread.run(HandlerThread.java:65)
12-26 12:12:35.249 25300 25907 W System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
12-26 12:12:35.249 25300 25907 W System.err:  at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646)
12-26 12:12:35.249 25300 25907 W System.err:  at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:605)
12-26 12:12:35.249 25300 25907 W System.err:  at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
12-26 12:12:35.249 25300 25907 W System.err:  at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
12-26 12:12:35.249 25300 25907 W System.err:  at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
12-26 12:12:35.249 25300 25907 W System.err:  at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
12-26 12:12:35.249 25300 25907 W System.err:  at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
12-26 12:12:35.249 25300 25907 W System.err:  at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:197)
12-26 12:12:35.249 25300 25907 W System.err:  at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:399)
12-26 12:12:35.249 25300 25907 W System.err:  at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
12-26 12:12:35.249 25300 25907 W System.err:  at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
12-26 12:12:35.249 25300 25907 W System.err:  at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
12-26 12:12:35.249 25300 25907 W System.err:  ... 13 more
12-26 12:12:35.249 25300 25907 W System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
12-26 12:12:35.249 25300 25907 W System.err:  ... 25 more
12-26 12:12:35.250 25300 25907 D OPrime  :  Unknown error uploading data to server
12-26 12:12:35.262  3518  3555 D StreamDBQueue: Promised revision #42625 to queue a new op
12-26 12:12:35.262  3518  3555 D BaseStreamManager: Promised set @ r#42625 for (com.github.old.fdb.speech.kartuli,tag=null,id=-1836701076,notifKey=0|com.github.old.fdb.speech.kartuli|-1836701076|null|10167)
12-26 12:12:35.264  3518  3566 D DynamicBucketRankerImpl: StreamItemId{notifKey=0|com.github.old.fdb.speech.kartuli|-1836701076|null|10167, packageName=com.github.old.fdb.speech.kartuli, id=-1836701076, revision=42625, originalRevision=42624, updateCount=1} in bucket #8 (Other)
12-26 12:12:35.264  3518  3566 D WatchStreamDB: com.google.android.clockwork.common.stream.TopLevelStreamItem@b96ec56 ranked at index 3
12-26 12:12:35.264  3518  3566 D NewStreamAdapter: Publishing revision #42625 to adapter clients
12-26 12:12:35.334  3518  3555 I NotificationBridger: Ignoring change event for bridged-notification data item
12-26 12:12:35.726  5584  5584 D StatusBar: disable<e i a s b h r c s q >

```

**Comment by cesine** [comment]
Uploads stopped after one year because we didn't update the certs in the app
```
new Date(1429485112811)
Mon Apr 20 2015 01:11:52 GMT+0200 (CEST)
```

**Comment by cesine** [comment]
TODO: update upload integration test to use best practices for testing a service that requires permissions
